version: '3.8'

services:
  # 1. Aplikasi Model & Monitoring
  app-inference:
    build: .
    container_name: ml_service_yusti
    ports:
      - "5000:5000" # Port untuk Inference API
      - "8000:8000" # Port untuk Metrics Prometheus (Wajib ada agar Prometheus bisa baca)
    volumes:
      - ../model_output:/app/model_output # Mounting model dari luar
    # Kita hapus baris 'command:' manual, agar Docker menggunakan CMD dari Dockerfile (yaitu ./start.sh)
    # command: python inference.py  <-- HAPUS INI

  # 2. Prometheus (Pencatat Data)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_yusti
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # 3. Grafana (Dashboard Grafik)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_yusti
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin